# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ASAPDemo-ObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
    pod 'ZohoDeskPortalServices', '3.0.0-beta.11'

  # Pods for ASAPDemo-ObjC

end
