# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ASAPDemo-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  

  pod 'ZohoDeskPortalAPIKit'
  pod 'ZohoDeskPortalConfiguration'
    
  pod 'ZohoDeskPortalKB'
  pod 'ZohoDeskPortalCommunity'
  pod 'ZohoDeskPortalTicket'
    
  pod 'ZohoDeskPortalCore'
    
  pod 'ZohoDeskPortalSalesIQ'
  pod 'ZohoDeskPortalChatKit'

  # Pods for ASAPDemo-Swift

end
