# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ASAPDemo-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Update to the latest version of the ASAP SDKs
  pod 'ZohoDeskPortalAPIKit', 'LATEST_VERSION'
  pod 'ZohoDeskPortalConfiguration', 'LATEST_VERSION'
    
  pod 'ZohoDeskPortalKB', 'LATEST_VERSION'
  pod 'ZohoDeskPortalCommunity', 'LATEST_VERSION'
  pod 'ZohoDeskPortalTicket', 'LATEST_VERSION'
    
  pod 'ZohoDeskPortalCore', 'LATEST_VERSION'
    
  pod 'ZohoDeskPortalSalesIQ', 'LATEST_VERSION'
  pod 'ZohoDeskPortalChatKit', 'LATEST_VERSION'

  # Pods for ASAPDemo-Swift

end
